Vagrant.configure("2") do |config|

  # Общие настройки для всех ВМ
  config.vm.box = "ubuntu/jammy64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus   = 2
  end

  config.vm.boot_timeout = 600

  # ───────────────────────────────────────────────
  # Nexus сервер (vm1)
  # ───────────────────────────────────────────────
  config.vm.define "vm1" do |vm1|
    vm1.vm.hostname = "vm1"

    vm1.vm.network "public_network",
      bridge:      "enp3s0",             
      ip:          "192.168.1.200",      
      netmask:     "255.255.255.0",
      promiscuous: "allow-all"

    vm1.vm.provision "shell", path: "scripts/install_nexus.sh"
    vm1.vm.provision "shell", path: "scripts/create_repos.sh"
  end

  # ───────────────────────────────────────────────
  # Клиент 1 (vm2)
  # ───────────────────────────────────────────────
  config.vm.define "vm2" do |vm2|
    vm2.vm.hostname = "vm2"

    vm2.vm.network "public_network",
      bridge:      "enp3s0",            
      ip:          "192.168.1.201",      
      netmask:     "255.255.255.0",
      promiscuous: "allow-all"

    vm2.vm.provision "shell", path: "scripts/setup_apt_client.sh"
  end

  # ───────────────────────────────────────────────
  # Клиент 2 (vm3) 
  # ───────────────────────────────────────────────
  config.vm.define "vm3" do |vm3|
    vm3.vm.hostname = "vm3"

    vm3.vm.network "public_network",
      bridge:      "enp3s0",             
      ip:          "192.168.1.202",      
      netmask:     "255.255.255.0",
      promiscuous: "allow-all"

    vm3.vm.provision "shell", path: "scripts/setup_apt_client.sh"
  end

end
